import React, { useState, useEffect, Children } from 'react';
import Head from 'next/head';

import styles from './PageContainer.module.css';

import Navbar from '@/components/Navbar/Navbar';
import LeftSidebar from '@/components/LeftSidebar/LeftSidebar';
import RightSidebar from '@/components/RightSidebar/RightSidebar';

export default function PageContainer(props) {
    const { children } = props;

    useEffect(() => {

    }, []);

    return (
        <>
            <Head>
                <title>ShareWithMe</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.main}>
                <div className={styles.container}>
                    <LeftSidebar />
                    <div className={styles.center}>
                        {children}
                    </div>
                    <RightSidebar />
                </div>
            </div>
        </>
    )
}